-- ==============================================================
-- File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.1
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ==============================================================

library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity read_from_string_cud_rom is 
    generic(
             dwidth     : integer := 6; 
             awidth     : integer := 7; 
             mem_size    : integer := 110
    ); 
    port (
          addr0      : in std_logic_vector(awidth-1 downto 0); 
          ce0       : in std_logic; 
          q0         : out std_logic_vector(dwidth-1 downto 0);
          clk       : in std_logic
    ); 
end entity; 


architecture rtl of read_from_string_cud_rom is 

signal addr0_tmp : std_logic_vector(awidth-1 downto 0); 
type mem_array is array (0 to mem_size-1) of std_logic_vector (dwidth-1 downto 0); 
signal mem : mem_array := (
    0 to 2=> "000010", 3 to 5=> "000011", 6 to 8=> "000000", 9 to 11=> "000001", 12 to 14=> "000101", 
    15 to 17=> "000100", 18 to 20=> "000110", 21 to 22=> "010001", 23 => "011010", 24 => "100000", 
    25 to 26=> "010000", 27 => "001000", 28 => "011001", 29 => "001000", 30 => "011101", 
    31 to 32=> "000111", 33 to 38=> "001001", 39 to 41=> "001010", 42 to 43=> "010011", 44 to 45=> "010100", 
    46 to 47=> "001100", 48 to 49=> "001011", 50 => "010010", 51 to 53=> "001000", 54 => "010010", 
    55 => "001000", 56 => "010001", 57 => "011011", 58 => "010001", 59 => "011010", 
    60 => "010101", 61 => "100000", 62 => "010110", 63 => "011001", 64 => "001101", 
    65 => "001110", 66 => "011101", 67 => "100011", 68 to 70=> "001100", 71 => "100100", 
    72 => "001100", 73 => "010011", 74 => "100101", 75 => "010011", 76 to 79=> "001111", 
    80 to 83=> "010010", 84 to 85=> "011011", 86 to 89=> "010111", 90 => "100011", 91 => "100001", 
    92 => "100100", 93 => "100001", 94 => "001111", 95 => "100101", 96 => "011110", 
    97 => "011111", 98 => "011000", 99 => "011100", 100 to 101=> "100010", 102 => "010111", 
    103 => "011010", 104 => "100000", 105 => "011001", 106 => "011101", 107 => "100011", 
    108 => "100100", 109 => "100101" );

attribute syn_rom_style : string;
attribute syn_rom_style of mem : signal is "select_rom";
attribute ROM_STYLE : string;
attribute ROM_STYLE of mem : signal is "distributed";

begin 


memory_access_guard_0: process (addr0) 
begin
      addr0_tmp <= addr0;
--synthesis translate_off
      if (CONV_INTEGER(addr0) > mem_size-1) then
           addr0_tmp <= (others => '0');
      else 
           addr0_tmp <= addr0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
        if (ce0 = '1') then 
            q0 <= mem(CONV_INTEGER(addr0_tmp)); 
        end if;
    end if;
end process;

end rtl;


Library IEEE;
use IEEE.std_logic_1164.all;

entity read_from_string_cud is
    generic (
        DataWidth : INTEGER := 6;
        AddressRange : INTEGER := 110;
        AddressWidth : INTEGER := 7);
    port (
        reset : IN STD_LOGIC;
        clk : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0));
end entity;

architecture arch of read_from_string_cud is
    component read_from_string_cud_rom is
        port (
            clk : IN STD_LOGIC;
            addr0 : IN STD_LOGIC_VECTOR;
            ce0 : IN STD_LOGIC;
            q0 : OUT STD_LOGIC_VECTOR);
    end component;



begin
    read_from_string_cud_rom_U :  component read_from_string_cud_rom
    port map (
        clk => clk,
        addr0 => address0,
        ce0 => ce0,
        q0 => q0);

end architecture;


