# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/adilr/Documents/fpga/finalproject/finalproject.cache/wt [current_project]
set_property parent.project_path C:/Users/adilr/Documents/fpga/finalproject/finalproject.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_repo_paths c:/Users/adilr/Documents/fpga/finalproject/finalproject.srcs [current_project]
set_property ip_output_repo c:/Users/adilr/Documents/fpga/finalproject/finalproject.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/adilr/Documents/fpga/finalproject/finalproject.srcs/sources_1/imports/src-vhdl/ascii_rom.vhd
  C:/Users/adilr/Documents/fpga/finalproject/finalproject.srcs/sources_1/imports/src-vhdl/delay.vhd
  C:/Users/adilr/Documents/fpga/finalproject/finalproject.srcs/sources_1/imports/src-vhdl/oled_ex.vhd
  C:/Users/adilr/Documents/fpga/finalproject/finalproject.srcs/sources_1/imports/src-vhdl/oled_ctrl.vhd
  C:/Users/adilr/Documents/fpga/finalproject/finalproject.srcs/sources_1/imports/src-vhdl/oled_init.vhd
  C:/Users/adilr/Documents/fpga/finalproject/finalproject.srcs/sources_1/imports/vhdl/read_from_string.vhd
  C:/Users/adilr/Documents/fpga/finalproject/finalproject.srcs/sources_1/imports/vhdl/read_from_string_bkb.vhd
  C:/Users/adilr/Documents/fpga/finalproject/finalproject.srcs/sources_1/imports/vhdl/read_from_string_cud.vhd
  C:/Users/adilr/Documents/fpga/finalproject/finalproject.srcs/sources_1/imports/vhdl/read_from_string_cud_ram.vhd
  C:/Users/adilr/Documents/fpga/finalproject/finalproject.srcs/sources_1/imports/vhdl/read_from_string_dEe.vhd
  C:/Users/adilr/Documents/fpga/finalproject/finalproject.srcs/sources_1/imports/vhdl/read_from_string_dEe_ram.vhd
  C:/Users/adilr/Documents/fpga/finalproject/finalproject.srcs/sources_1/imports/vhdl/read_from_string_eOg.vhd
  C:/Users/adilr/Documents/fpga/finalproject/finalproject.srcs/sources_1/imports/src-vhdl/spi_ctrl.vhd
  C:/Users/adilr/Documents/fpga/finalproject/finalproject.srcs/sources_1/new/pattern_rec.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/adilr/Documents/fpga/finalproject/finalproject.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files C:/Users/adilr/Documents/fpga/finalproject/finalproject.srcs/constrs_1/new/constraints.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top pattern_rec -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef pattern_rec.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file pattern_rec_utilization_synth.rpt -pb pattern_rec_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
